provider_config:
  bms:
#    ssh_pwd: root
#    ssh_user: s0e1a2n3
#    ssh_public_key: /root/.ssh/id_rsa.pub
#    ssh_private_key: /root/.ssh/id_rsa
instances:
  bms1:
    provider: bms
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      vrouter:
        VROUTER_GATEWAY: 192.168.33.1
        PHYSICAL_INTERFACE: enp0s8
      kubemanager:
      k8s_master:
      k8s_node:
      openstack:
      openstack_compute:
    ip: 192.168.33.100
global_configuration:
  CONTAINER_REGISTRY: opencontrailnightly
#  CONTAINER_REGISTRY: tungstenfabric
#  K8S_VERSION: "1.18.17"
  K8S_VERSION: "1.20.4"
  K8S_DASHBOARD_VERSION: "2.2.0"
contrail_configuration:
  CONTRAIL_VERSION: latest
#  JVM_EXTRA_OPTS: "-Xms128m -Xmx2g"
#RABBITMQ_NODE_PORT: 5673
  AUTH_MODE: keystone
  #  KEYSTONE_AUTH_URL_VERSION: /v3
  #KEYSTONE_AUTH_ADMIN_PASSWORD: contrail123
  #CLOUD_ORCHESTRATOR: openstack
  #  VROUTER_GATEWAY: 192.168.33.1
  #  PHYSICAL_INTERFACE: enp0s8

kolla_config:
  customize:
    nova.conf: |
      [libvirt]
      virt_type=qemu
      cpu_mode=none
  kolla_globals:
    network_interface: enp0s8
    kolla_internal_vip_address: "192.168.33.100"
    kolla_external_vip_address: "192.168.33.100"
    enable_haproxy: no
    enable_ironic: no
    enable_swift: no
    enable_barbican: no
  kolla_passwords:
    keystone_admin_password: "s0e1a2n3"
