provider_config:
  bms:
#    ssh_pwd: root
#    ssh_user: s0e1a2n3
#    ssh_public_key: /root/.ssh/id_rsa.pub
#    ssh_private_key: /root/.ssh/id_rsa
instances:
  bms1:
    provider: bms
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      vrouter:
        VROUTER_GATEWAY: 10.0.2.3
        PHYSICAL_INTERFACE: enp0s3
      kubemanager:
      k8s_master:
      k8s_node:
    ip: 10.0.2.15
global_configuration:
  CONTAINER_REGISTRY: opencontrailnightly
#  CONTAINER_REGISTRY: tungstenfabric
#  K8S_VERSION: "1.18.17"
  K8S_VERSION: "1.20.4"
  K8S_DASHBOARD_VERSION: "2.2.0"
contrail_configuration:
  CONTRAIL_VERSION: latest
#  JVM_EXTRA_OPTS: "-Xms128m -Xmx2g"
